### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by odomfavour**

### CODE REVIEW

**Comment by odomfavour** [comment]
I added the reset password, forgot password and profile page
screencapture-127-0-0-1-5500-forgotpassword-html-2020-03-04-11_10_27
screencapture-127-0-0-1-5500-profile-html-2020-03-04-11_10_57
screencapture-127-0-0-1-5500-resetpassword-html-2020-03-04-11_12_03

**Comment by tochiOz** [comment]
Are You sure these guys are responsive?
Secondly, the design is still looking dull, please oo, work on the footer, the REACH US On section, please create more space let the address and contact lap well probably on a straight Line

**Comment by tochiOz** [comment]
Lastly, still, on the footer the WRITE TO US section is really not necessary, take it out find something to put there. since there is a contact page they can reach us therefrom that page., please rearrange that footer its looking some how

**Comment by tochiOz** [comment]
Next, fonts, please go to google fonts and get me fine fonts, the site should not be using anyhow fonts because its a money site

**Comment by tochiOz** [comment]
COLOUR????, who chose the color???, are we in a burial or what, PLease the general color should be readdressed

**Comment by tochiOz** [comment]
Make i no talk again. The changes needs to be addressed before i can merge any other pull request

**Pull request merged**
